### ISSUE TITLE
Create a blind app inspired by a Nillion tinydemo library

### ISSUE THREAD

**Issue by oceans404** [NillionNetwork/builder-bounties#3]
## Description

Create a blind app inspired by a Nillion tinydemo library (**tinybid** auction, **tinybio** biometric auth, **tinybin** API data integration)

![Image](https://github.com/NillionNetwork/builder-bounties/assets/91382964/25efc57f-1dff-4ece-8004-2a947231ac08)

## Requirements

1. Take a look at our 3 existing repos tinybid - blind auction, tinybio - biometric authentication, and tinybin - api call. These repos don't use Nada yet. Use one of these 3 existing repos, [tinybid](https://github.com/NillionNetwork/tinybid), [tinybio](https://github.com/NillionNetwork/tinybio), or [tinybin](https://github.com/nillionnetwork/tinybin), as inspiration to create a local Nillion blind application that solves a novel and imaginative use case that you define. Your Nillion blind app (frontend + [Nada programs](https://docs.nillion.com/nada-lang-programs) should meet these requirements:
    1. Come up with a novel use case for your [Nada programs](https://docs.nillion.com/nada-lang-programs) based on the 💡ideas below.
    2. Your frontend uses the Nillion [JavaScript Client](https://docs.nillion.com/js-client) to compute with your Nada program(s). Hook this up to either the existing frontend demo code or a frontend demo you create tailored to your novel use case. Hint: try Nillion’s scaffold-nillion NextJS starter repo within the [JavaScript Developer Quickstart](https://docs.nillion.com/js-quickstart).
    3. All code is in an open source repo.
2. Create a video walkthrough to demo your build.
3. Submit your open source repo and video by creating a new post in the "Show and Tell” category of our [Nillion Github Discussions](https://github.com/orgs/NillionNetwork/discussions)
4. Reply to the [Farcaster bounty post](https://warpcast.com/oceans404/0x992de78b) with a link to your ["Show and Tell” Github discussions post](https://github.com/orgs/NillionNetwork/discussions)

### 1. **tinybid** 

- implements a basic single-item first-price **auction**
- 💡 ideas: allow the user to choose between a number of different types of auction (e.g. Vickrey, Dutch, English auctions), allow winning bidders to connect their wallet to pay
- library code: https://github.com/NillionNetwork/tinybid
- demo: https://nillion.pub/tinybid/
- frontend demo code: https://github.com/NillionNetwork/tinybid/tree/gh-pages

To qualify for the tinybid bounty, you could write a Nada program that does some form of an auction where each secret is a bid amount from a different bidder and returns the highest bid and the winning bidder. Connect that program to a frontend so bidders can submit their bids

### 2. **tinybio** 
- implements a basic version of a secure decentralized **biometric authentication**
- 💡 ideas: a biometric login solution that allows users access to another application or data store
- library code: https://github.com/NillionNetwork/tinybio
- demo: https://nillion.pub/tinybio/
- frontend demo code: https://github.com/NillionNetwork/tinybio/tree/gh-pages

To qualify for the tinybio bounty, you could write a Nada program that compares 2 sets of points, each of which is a secret input. Your frontend could use an existing auth api to get the facial points from an image or webcam) and feeds these to the Nada program to compute how close or far apart they are to decide if they are the same face.

### 3. **tinybin**

- demonstrates how to integrate a **3rd party API** by sending an HTTP request to https://httpbin.org/ and compares the output to a private input
- 💡ideas: obtain price data from the Nasdaq API, data on Tweets or map data and compare against a private value. This is your chance to really let your imagination go wild. Be careful not to use an API that collects user data in the clear, as this is against Nillion’s privacy philosophy 😎
- demo: https://nillion.pub/tinybin/
- code: https://github.com/nillionnetwork/tinybin
- frontend demo code: https://github.com/NillionNetwork/tinybin/blob/main/index.html
- suggested data flow:
        1. pull data from any api
        2. feed api data to nada program
        3. perform logic with api data vs secrets stored in nillion

To qualify for the tinybin bounty you could write a Nada program that compares a secret user input to an input from an api. One example could be a weather guessing app. For a weather guessing app, you could compare what a user secretly guesses the temperature will be tomorrow to an input that is the api call result of tomorrow's weather. The frontend would be where the user places a guess at tomorrow's temperature, stored as a secret input.

## Rewards

- 2,000 USDC for the best app that is inspired by Nillion’s tinybid library
- 2,000 USDC for the best app that is inspired by Nillion’s tinybio library
- 2,000 USDC for the best use of any third-party API with blind computation, inspired by Nillion’s tinybin library

### Judging Criteria

Nillion will award one 2,000 USDC prize per bounty. The best project for each bounty category will be chosen considering the following:

- Cleanest and most efficient nada programs
- Overall clean and well documented code
- Polished UX and UI on the frontend to make it intuitive and fun for the user to use
- Best explanation of project within Github Discussions Show and Tell post and video demo

Questions about bounty requirements? Ask us [on Discord](https://discord.com/channels/905926225120338000/1204182721987878962) or [Github discussions](https://github.com/orgs/NillionNetwork/discussions/categories/q-a)

**Comment by ofemeteng** [comment]
Are there any updates on the results?
The announcement on Farcaster said we should expect the unveiling of bounty winners this week.
@oceans404

**Comment by oceans404** [comment]
## Congratulations to our bounty winners

Results tweet: https://x.com/nillionnetwork/status/1820606184895947087

### tinybid winner
2,000 USDC to @daningyn who built Mona Lisa Art Auction inspired by tinybid: https://github.com/orgs/NillionNetwork/discussions/67

### tinybio winners

1,000 USDC to @Envoy-VC who built a Transcend Vault blind app: https://github.com/orgs/NillionNetwork/discussions/62
1,000 USDC to @OmarAlmighty who built a private facial recognition system for biometric authentication https://github.com/orgs/NillionNetwork/discussions/71


### tinybin winner

2,000 USDC to @kanav99 who built a blind app that does private inference of an MNIST model: https://github.com/orgs/NillionNetwork/discussions/60

---

we'll send your prizes via the ETH addresses you provided this Friday!
